cam-inc/viron

- src/css/pages/ComponentsPage_Card_Table.css
- #293
- アイコンの背景グラデを調整
Before | After
:--: | :--:
> テーブルcell操作用アイコンの背景グラデを調整

- src/pages/viron-components/operation/index.js
-
submitボタン連打で同じ内容のpostが行われるため、confirmSubmit()内でフラグ管理を行いsubmit処理を複数行わないよう制御する
-
Before | After
:--: | :--:
> Disable duplicate post  on submit button

- src/pages/viron-components/card/table/cell/index.js
- Image URLs are shown as text if they are not suffixed with one of the image extensions
- Treat table cell as image if format is `image-url`
-
Before | After
:--: | :--:
> Treat table cell as image if format is `image-url`

- src/components/viron-wyswyg/index.js
- The default font size(11pt) can not be selected from the menu, so i added.
- https://www.tiny.cloud/docs/configure/content-formatting/#fontsize_formats
Before | After
:--: | :--:
> Fix bug of editor font size selection

- src/css/components/Wyswyg.css
- none
- fix wysiwyg preview itemize
- none
Before | After
:--: | :--:
> Wysiwyg preview itemize

- .dockerignore
I happend wait for very longtime on docker build.
The cause I guess is content synchronization to the container.
Thanks.
-
-
Before | After
:--: | :--:
> node_modules and .git are not required for build

- example/nodejs/src/application.ts
- example/nodejs/src/constant.ts
- example/nodejs/src/handlers/unauthorized.ts
- example/nodejs/src/routes/index.ts
- packages/nodejs/src/constants.ts
- `/viron_authtypes` をサーバ側から指定する
- `401: unauthorized` を返すときのレスポンスヘッダに `authtypes` のパスを返すようにした
-
Before | After
:--: | :--:
> `authtypes`  のパスを401のときのレスポンスヘッダで指定する

- example/nodejs/src/openapi/ping.yaml
- example/nodejs/src/openapi/root.yaml
- example/nodejs/src/routes/auditlogs.ts
- example/nodejs/src/routes/authtypes.ts
- example/nodejs/src/routes/index.ts
- example/nodejs/src/routes/oas.ts
- example/nodejs/src/routes/ping.ts
- example/nodejs/src/routes/root.ts
- example/nodejs/src/routes/viron.ts
- packages/nodejs/src/openapi/auditlogs.yaml
- packages/nodejs/src/openapi/authtypes.yaml
- packages/nodejs/src/openapi/oas.yaml
- packages/nodejs/src/openapi/viron.yaml
- `swagger` => `oas` に統一
- `operationId` を全体でユニークになるように調整
-
-
Before | After
:--: | :--:
> Refactor: rename swagger to oas, unique operationId

- example/nodejs/package.json
- example/nodejs/src/openapi/articles.yaml
- example/nodejs/src/openapi/components.yaml
- example/nodejs/src/openapi/purchases.yaml
- example/nodejs/src/openapi/users.yaml
- example/nodejs/src/stores/definitions/mongo/articles.ts
- example/nodejs/src/stores/definitions/mongo/purchases.ts
- example/nodejs/src/stores/definitions/mongo/users.ts
- package-lock.json
- packages/nodejs/package.json
- packages/nodejs/src/openapi/adminaccounts.yaml
- packages/nodejs/src/openapi/adminroles.yaml
- packages/nodejs/src/openapi/adminusers.yaml
- packages/nodejs/src/openapi/auditlogs.yaml
- packages/nodejs/src/openapi/authconfigs.yaml
- packages/nodejs/src/openapi/components.yaml
- packages/nodejs/src/stores/definitions/mongo/adminusers.ts
- packages/nodejs/src/stores/definitions/mongo/auditlogs.ts
- packages/nodejs/src/stores/definitions/mongo/revokedtokens.ts
> Fix: timestamp

- packages/golang/helpers/oas.go
- vrionのfrontにoas返却する際に ./components.yamlなど別ファイルrefの記述になってしまう。
- schemaのpropertiesも置換するようにした。
> 🐛Fix：components.schema.propertiesのrefが置換されない

- .gitignore
- example/golang/routes/middleware.go
- example/golang/routes/routes.go
- packages/golang/domains/auth/googleauth.go
- packages/golang/domains/auth/jwt.go
- packages/golang/domains/auth/jwt_test.go
- verifyのhttp.Requestのinjectionが必要
- verifyでiss audは自分でチェックしないとchiのjwtauth.VerifyTokenではチェックしない
- exampleでACLAllowのcheckタイミングをadminuser.authの後にしないとadminuserが取れない
> 🐛Fix：jwt iss aud injection verify

- packages/golang/routes/oas/oas.go
- oasApiのレスポンスヘッダーに`x-viron-authtypes-path` を追加
- vironのトップ画面から各oasを取得する際にこける
```
Endpoint Error
[#endpoint]
The x-viron-authtypes-path response header is missing.
```
- node側の対応 https://github.com/cam-inc/viron/pull/528/files
> 🐛Fix：add x-viron-authtypes-path to oasapi response header

- package-lock.json
- packages/nodejs/package.json
- packages/nodejs/src/repositories/index.ts
update  casbin-mongoose-adapter `3.0.1` → `4.0.2`
casbin-mongoose-adapter support Mongoose 6.x from `4.0.0`
https://github.com/node-casbin/mongoose-adapter/blob/master/CHANGELOG.md#400-2022-01-29
> update casbin-mongoose-adapter version

- packages/golang/domains/adminroles.go
管理ロール更新時、管理ロールをアタッチしているユーザーからロールが消えるバグの修正
update時の`removeRole()`で[groupingPolicy(ptype: g)](https://casbin.org/docs/en/policy-storage#database-storage-format)まで消してた
- [RemovePolicies()](https://casbin.org/docs/en/management-api#removepolicies)でpolicyのみ削除できるようにした
- adminRoleのcreateとupdateの処理を`UpdatePermissionsForRole()`で共通に行っていたが、`CreatePermissionsForRole()`と`UpdatePermissionsForRole()`で分けた(createとupdateでやりたい事が異なるため)
> 🐛Fix：adminRole bug

- package-lock.json
- packages/nodejs/CHANGELOG.md
- packages/nodejs/package.json
update casbin-mongoose-adapter 4.0.2 →  5.1.0
This version up includes the change `p_type` to `ptype` in `casbin_role` collection.
https://github.com/node-casbin/mongoose-adapter/blob/master/CHANGELOG.md#breaking-changes
- https://github.com/cam-inc/viron/issues/602
> upgrade casbin mongoose adapter to 5.1.0

- packages/golang/domains/oas.go
- packages/golang/domains/oas_test.go
operationIdを取得する処理([findOperationIDByPathMethod](https://github.com/cam-inc/viron/blob/d87669e705110f182253989ea55962edf16070d6/packages/golang/domains/oas.go#L191-L210))を修正
現状下記のパターン時に、`/user`に紐づくoperationIdを返してしまう
```
実際のリクエストパス -> /users
oasで定義されてるパス -> /user 
```
> 🐛Fix：process to get operaitonId

- packages/golang/domains/oas.go
複数ロールが付与されたユーザーの場合に一覧画面で同じテーブルビューが２つ表示されてしまう
oas返却APIで複数ロール分ループでpages.ContentsのパーミッションチェックしてOKならbreakするようにして
2つContentができないようにした
> 🐛Fix:ロールが複数の場合リストテーブルが２つ表示される

- package-lock.json
- package.json
- bump husky version to v8
- skip husky install
-  remove pinst
- Viron use npm and changed from postinstall to prepare
- https://github.com/typicode/pinst
> skip husky install

- codepipeline/app-buildspec.yml
- codepipeline/snapshot-app-buildspec.yml
An error occurred when building with develop.
```
failed Building production JavaScript and CSS bundles - 48.115s
error Generating JavaScript bundles failed
Can't resolve '@viron/linter' in '/codebuild/output/src017160690/src/codestar-connections.ap-northeast-1.amazonaws.com/git-http/394319427766/ap-northeast-1/c6e371fb-3561-4734-bfff-5db5eae4f396/cam-inc/viron/packages/app/src/utils/oas'
If you're trying to use a package make sure that '@viron/linter' is installed. If you're trying to use a local file make sure that the path is correct.
```
I have confirmed that the build was successful on my PC by following the same procedure as with this modification.
> fix: build flow

- codepipeline/app-deployspec.yml
- package-lock.json
- packages/app/package.json
An error arises when executing npm install within the CI/CD environment. Resolving the conflicting peer dependencies may potentially rectify this issue. 
The conflict in peer dependencies involves @types/jest and React. Although the issue with @types/jest was successfully resolved, addressing the conflict with React proved to be challenging due to StoryBook (in the current installed version) relying on versions "^16.8.4 || ^17.0.0". I endeavored to update the version of StoryBook; however, the process was not as straightforward as anticipated. 
Ultimately, I resolved the conflicting peer dependencies as much as possible and added the "--legacy-peer-deps" option.
> Resolving Conflicting Peer Dependencies

- .changeset/unlucky-panthers-rule.md
- packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/item/signin/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/item/signout/index.tsx
signin and signout buttons changed to renewal.
url: [https://localhost:8000/dashboard/endpoints/](https://localhost:8000/dashboard/endpoints/)
before|after
-|-
-|-
-|-
> fix: signin and signout buttons changed to renewal 

- .changeset/kind-readers-invent.md
- packages/app/src/components/button/outline/index.tsx
- packages/app/src/components/button/outline/on/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/add/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
- packages/app/src/pages/dashboard/groups/_/body/add/index.tsx
- packages/app/src/pages/dashboard/groups/_/body/item/index.tsx
Replaced AddEndpointButton from FilledButton to OutlineButton.
OutlineButton's outline color was not &{cs}-low, so the color was changed.
Created a new OutlineOnButton.renewal component and accordingly changed the on of the old OutlineButton's Props to cs.
before|after
--|--
> fix: replace addEndpointButton

- .changeset/friendly-years-serve.md
- packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/item/signout/index.tsx
Added changes to components due to changes to OutlineButton.
before|after
-|-
> fix: signout button

- .changeset/quick-pans-run.md
- packages/app/src/components/head/index.tsx
- packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
Renewed design of Head component on dashboard page.
before|after
-|-
> fix: head component

- .changeset/thick-files-explain.md
- packages/app/src/components/tabs/index.tsx
- packages/app/src/pages/dashboard/_/tabs/index.tsx
- packages/app/src/pages/dashboard/groups/_/body/index.tsx
Renewed the design of the Tabs component on the dashboard page
before|after
-|-
> fix: dashboard tabs

- packages/app/src/pages/dashboard/groups/_/body/index.tsx
Renewed Head component and AddEndpointButton component on dashboard/groups page.
before|after
--|--
> feat: renewed groups page

- .changeset/gold-stingrays-march.md
- packages/app/src/components/icon/download/outline/index.tsx
- packages/app/src/components/icon/upload/outline/index.tsx
- packages/app/src/pages/dashboard/_/appBar/export/index.tsx
- packages/app/src/pages/dashboard/_/appBar/import/index.tsx
Renewed appBar button.
Added "download" and "upload" icons.
before|after
--|--
> Fix: appbar button

- .changeset/proud-experts-guess.md
- package-lock.json
- packages/app/package.json
- packages/app/src/wrappers/page.tsx
It's hard to keep i18n language data while oauth redirecting, because oauth redirect url is constants.
I added i18n auto redirect function so that when coming back to oauth redirect url it will redirect to the page with language prefix.
> fix: i18n redirect function

- .changeset/tame-parrots-fix.md
- packages/app/src/components/navigation/internalPages/index.tsx
- packages/app/src/components/navigation/links/index.tsx
- packages/app/src/components/navigation/services/index.tsx
- packages/app/src/pages/dashboard/_/navigation/index.tsx
Renewed internalPages of navigation component.
Changed font size to 14px and changed icon size setting accordingly.
※The issue of navigation not being active when on the /dashboard/endpoints page is not addressed in this PR, as it may require significant changes.
before|after
-|-
> fix: internal pages component

- .changeset/big-dingos-work.md
- packages/app/src/layouts/index.tsx
- packages/app/src/pages/endpoints/[endpointId]/_/appBar/index.tsx
- Fix: Sidebars overlapping pinned panels 
- Fix: Scrolling overlaps breadcrumbs UI and Table
before|after
-|-
> Fix: Sidebars overlapping pinned panels 

- .changeset/five-lobsters-hammer.md
- packages/app/src/components/table/cell/string/index.tsx
https://discovery.viron.plus/docs/Advanced-Guides/content-table#data-display
The official documentation described the data type uri of the table cell.
However, it was not implemented.
In this PR, the case where the data type is uri is added.
> feat: content table uri

- .changeset/four-jokes-switch.md
- packages/app/src/components/schema/hooks/index.ts
Fixed a bug that could cause a list of autocompletes for different forms to be displayed when using multiple autocompletes at the same time.
The cause was that when using Date.now() to generate autocompleteId, there was a high probability that the same id would be generated for a nearby form.
The id generation logic mimics the following code.
https://github.com/cam-inc/viron/blob/7607169afce6b8c9164bc4c2aa5550ba7a8f3149/packages/app/src/components/textinput/index.tsx#L45
> Fixed a bug that caused different form autocomplete listings to be displayed

- .changeset/tall-bikes-invite.md
- packages/app/src/pages/endpoints/[endpointId]/_/content/index.tsx
Apply overflow style to content container to clip container body to show a border edge completely.
Provide references that relate to your PR, if any.
> fix(app): border-bottom are chipped if container doesn't have a pager 🐛

- .changeset/cold-apes-drum.md
- packages/app/src/pages/oauthredirect/_/body/index.tsx
The spinner in the oauthredirect page placed left edge unnaturally. Fixed to place it to center.
> fix(app): spinner is unnaturally placed on the far left 🐛

- .changeset/thick-forks-behave.md
- packages/app/src/pages/dashboard/endpoints/_/body/item/thumbnail/index.tsx
Endpoints typically incorporate specific access systems. This may lead to a persistent risk of associated thumbnails failing to display. 
Particularly, if the thumbnail URL is inaccessible, the broken image tag remains unaffected.
Therefore, decided to replace it to Viron’s logo as default.
> fix(app): broken x-thumbnail will be displayed as is 🐛

- .changeset/cold-apes-drum.md
- .changeset/thick-forks-behave.md
- package-lock.json
- packages/app/CHANGELOG.md
- packages/app/package.json
- 4204d2d2: Move spinner to the center to natural position.
- 77798b09: Hide broken x-thumbnail if error was thrown.
> version: update app

- example/nodejs/Dockerfile
Now, accessing to demo site(https://demo.viron.plus)  returns 503 due to container is not started.
This is because that /example/nodejs/.npm folder created with root owned folder.
So, we need to define `USER node` before `RUN npm install` in Dockerfile.
updated folder permission is bellow:
```
node@182909fc783b:~$ ls -al
total 1020
drwxr-xr-x   1 node node   4096 Jan  8 16:22 .
drwxr-xr-x   1 node node   4096 Jan  8 15:44 ..
drwxr-xr-x   3 node node   4096 Jan  8 16:20 .cache
drwxr-xr-x   1 node node   4096 Jan  8 16:18 .npm
drwxr-xr-x   2 node node   4096 Jan  8 15:28 cert
drwxr-xr-x  14 node node   4096 Jan  8 16:22 dist
drwxr-xr-x 679 node node  20480 Jan  8 16:20 node_modules
-rw-r--r--   1 node node 982233 Jan  8 16:20 package-lock.json
-rw-r--r--   1 node node   3771 Jan  8 15:28 …
```
> fix: permission error.

- .changeset/itchy-pens-protect.md
- packages/app/src/components/numberinput/index.tsx
- packages/app/src/components/select/index.tsx
- packages/app/src/components/textarea/index.tsx
- packages/app/src/components/textinput/index.tsx
Adjusted input form padding.
before|after
-|-
- [-] [changeset file(s)](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) included
> fix(app): add padding to input form

- .changeset/cool-planes-clap.md
- packages/app/src/components/button/index.tsx
align the label inside the button to the left.
|before|after|
|-|-|
https://www.notion.so/cyberagent-group/export-import-a3baebb9db5544708c15e0c6e30c0691
> fix(app): align the label inside the button to the left

- .changeset/fair-pears-tap.md
- packages/app/src/components/button/index.tsx
- packages/app/src/pages/dashboard/_/menu/index.tsx
align the label inside the button to the left.
|before|after|
|-|-|
https://www.notion.so/cyberagent-group/export-import-a3baebb9db5544708c15e0c6e30c0691
> Fix import and export button style

- package-lock.json
- packages/nodejs/package.json
```
src/domains/oas.ts(11,33): error TS2307: Cannot find module '@apidevtools/json-schema-ref-parser' or its corresponding type declarations.
--
88 | src/domains/oas.ts(15,22): error TS2307: Cannot find module '@viron/linter' or its corresponding type declarations.
89 | src/domains/oas.ts(236,29): error TS7006: Parameter 'error' implicitly has an 'any' type.
90 | src/domains/oas.ts(236,36): error TS7006: Parameter 'i' implicitly has an 'any' type.
```
fix build package error to update dependent pacakges
> fix(nodejs): chore update

- .github/workflows/package-nodejs-viorn-lib-publich.yml
- .github/workflows/publish-package-viorn-lib.yml
- .github/workflows/publish-package-viorn-linter.yml
- package-lock.json
- packages/nodejs/CHANGELOG.md
- packages/nodejs/__tests__/domains/adminrole.test.ts
- packages/nodejs/package.json
- move cicd to GitHub action
- fix flaky test
- fix dependencies for Mongoose 
I already released the alpha SDK and debugged it and it works fine.
> move npm publish to github action

- example/nodejs/package.json
- example/nodejs/src/infrastructures/s3/client.ts
- package-lock.json
This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).
```console
$ npx aws-sdk-js-codemod@0.28.2 -t v2-to-v3 example/**/*.ts
```
From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.
> chore: migrate AWS SDK for JavaScript v2 APIs to v3

- .changeset/old-insects-occur.md
- package-lock.json
- packages/nodejs/package.json
- packages/nodejs/src/helpers/cookies.ts
Prepare for 3rd paty cookie deprecation using Independent Partitioned State (CHIPS)
Partitioned attribute of cookies is currently not supported in go
- https://github.com/golang/go/issues/62490
> Prepare for 3pcd

- .changeset/spotty-kangaroos-shout.md
- packages/nodejs/src/helpers/cookies.ts
Set the default setting of patition to false until all 3pcd support is complete, as it may prevent login under certain conditions.
> Fix default partitioned cookie

- .changeset/rich-beers-worry.md
- packages/app/src/components/fileReader/index.tsx
Fixed a bug that could cause different FileReaders to be selected when using multiple FileReaders.
The cause of this bug is that the same id could be assigned to adjacent FileReaders due to the use of `Date.now()` for id generation.
https://github.com/cam-inc/viron/pull/755
https://github.com/cam-inc/viron/issues/779
> Fixed a bug that caused different fileReader to be selected

- .changeset/fast-apples-switch.md
- packages/app/src/types/index.ts
Provide options for future 3pcd support where navigation would necessarily occur at present.
https://github.com/cam-inc/viron/pull/829
> feat: add mode prop to determine how to opening the OAuth endpoint ✨

- packages/golang/domains/adminroles.go
- packages/golang/domains/adminroles_test.go
loadPolicy fails if casbin data contains a comma
N/A
> fix: loadPolicy fails if casbin data contains a comma

- example/nodejs/Dockerfile
The Docker image build for the example package failed because Turborepo was not taken into consideration.
> fix: missing build step handling for when Turborepo is used 🐛

- .changeset/little-feet-remember.md
- example/nodejs/src/controllers/auth.ts
- example/nodejs/src/controllers/authconfigs.ts
- packages/app/src/hooks/endpoint.ts
- packages/nodejs/src/constants.ts
- packages/nodejs/src/domains/authconfig.ts
- packages/nodejs/src/helpers/cookies.ts
- packages/nodejs/src/openapi/auth.yaml
- packages/nodejs/src/openapi/authconfigs.yaml
- packages/website/docs/04-Advanced-Guides/authentication.md
- packages/website/i18n/ja/docusaurus-plugin-content-docs/current/04-Advanced-Guides/authentication.md
In preparation for the future deprecation of third-party cookies, we've designed a new sign-in flow. 
The new AuthConfig can return a mode property, which indicates whether the front-end should trigger a top-level navigation or initiate the sign-in flow via a Fetch request.
The Viron endpoint also needs to support sign-in via Fetch by returning the URL in the response body.
> feat: support CHIPS to resolve 3pcd ✨

- codepipeline/app-buildspec.yml
- codepipeline/app-deployspec.yml
- codepipeline/snapshot-app-buildspec.yml
- codepipeline/snapshot-app-deployspec.yml
We've decided to use the latest version of Node.js. While this may introduce a risk of build failures, we can detect such issues since the environment is under our control.
This decision prioritizes reducing the risk of unintentionally continuing to use outdated versions.
> feat: use latest nodejs to build and deploy app ✨
