cam-inc/viron

src/css/components/List.css

- #282
- 3点リーダー内のボーダー色を変更
Before | After
:--: | :--:

3点リーダー内のボーダー色を変更

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

PR毎にISSUEなど書いていたので、Templateを追加
テスト↓
https://github.com/MuuKojima/kojimation-web/pull/37

PRとISSUEテンプレートの追加

---

src/pages/viron-components/card/table/index.js

- #318 
-
-
Before | After
:--: | :--:

Fixed: reset pagination parameters when search queries are updated.

---

demo/swagger/swagger.yaml
src/pages/viron-components/operation/index.js

- #197
- Make it possible to set a custom label to a execution buttons

Updated: name of submit button can be changed.

---

src/components/viron-textinput/index.js
src/viron/header/menu/entry/index.js
src/viron/header/menu/entry/index.tag

- #182
- Make it possible for submit btn to submit by Enter key at endpoint page

Added: make it possible for submit btn to submit by Enter key at endpoint page

---

src/pages/viron-endpoints/endpoint/signin/email/index.js
src/pages/viron-endpoints/endpoint/signin/email/index.tag

- #182
- Enable signin form  to submit by enter key.

Enable signin form  to submit by enter key.

---

src/components/viron-autocomplete/index.js
src/components/viron-numberinput/index.js
src/components/viron-parameters/form/index.js
src/components/viron-parameters/form/index.tag
src/components/viron-parameters/index.js
src/components/viron-parameters/index.tag
src/components/viron-parameters/items/index.js
src/components/viron-parameters/items/index.tag
src/components/viron-parameters/parameter/index.js
src/components/viron-parameters/parameter/index.tag
src/components/viron-parameters/properties/index.js
src/components/viron-parameters/properties/index.tag
src/components/viron-textinput/index.js
src/components/viron-textinput/index.tag
src/pages/viron-components/operation/index.js
src/pages/viron-components/operation/index.tag

- #182
- Enable enter key to submit in viron-parameters component
- First should merge this [PR](https://github.com/cam-inc/viron/pull/324)

Enable enter key to submit in viron-parameters component

---

src/components/viron-select/index.tag
src/css/components/Numberinput.css
src/css/components/Select.css
src/css/components/Textarea.css
src/css/components/Textinput.css

- #313
- Change some colors like border, text, placeholder in form components.

Change some colors of form components.

---

src/components/viron-wyswyg/index.js

Fixed: change event for mobile devices.

---

Dockerfile

- Local web server dies with exception when trying [quick start](https://cam-inc.github.io/viron-doc/docs/dev_quickstart.html).
- Added some files which is required to run local web server 
-
Before | After
:--: | :--:

fixed lack of files to run local web server.

---

demo/controllers/user.js
demo/controllers/viron.js
demo/shared/constant.js
demo/swagger/swagger.yaml
src/css/pages/ComponentsPage_Card_Table.css
src/pages/viron-components/card/table/index.js
src/pages/viron-components/card/table/index.tag
src/store/getters/components.js

-
-
-
Before | After
:--: | :--:

Table filter

---

.vscode/launch.json
example/nodejs/.eslintignore
example/nodejs/.eslintrc.js
example/nodejs/.gitignore
example/nodejs/.prettierrc.yaml
example/nodejs/Dockerfile
example/nodejs/README.md
example/nodejs/k8s/deployment.yaml
example/nodejs/package-lock.json
example/nodejs/package.json
example/nodejs/skaffold.yaml
example/nodejs/src/application.ts
example/nodejs/src/route/ping.ts
example/nodejs/src/server.ts
example/nodejs/tsconfig.json

-
-
-
Before | After
:--: | :--:

New: 🎉 init example on nodejs

---

example/nodejs/README.md
example/nodejs/k8s/comfigmap-mongo.yaml
example/nodejs/k8s/comfigmap-mysql.yaml
example/nodejs/k8s/deployment-mongo.yaml
example/nodejs/k8s/deployment-mysql.yaml
example/nodejs/k8s/deployment.yaml
example/nodejs/package.json
example/nodejs/skaffold.yaml
example/nodejs/src/routes/ping.ts

-
-
-
Before | After
:--: | :--:

Example nodejs

---

example/nodejs/.eslintrc.js
example/nodejs/.gitignore
example/nodejs/package-lock.json
example/nodejs/package.json
example/nodejs/src/server.ts

- eslintの警告が出まくってた
- 出ないようにした
-
Before | After
:--: | :--:

とりあえずeslint通した

---

.gitignore
.npmrc

-
-
-
Before | After
:--: | :--:

Remove: .npmrc

---

example/nodejs/package-lock.json
example/nodejs/package.json
example/nodejs/src/application.ts
example/nodejs/src/openapi.yaml
example/nodejs/src/routes/index.ts
example/nodejs/src/security_handlers/index.ts
example/nodejs/src/security_handlers/jwt.ts

-
- Openapiサポート
-
Before | After
:--: | :--:

Add: express-openapi

---

example/nodejs/mysql.env
example/nodejs/package-lock.json
example/nodejs/package.json
example/nodejs/src/configure.ts
example/nodejs/src/context.ts
example/nodejs/src/errors.ts
example/nodejs/src/lib/stores/definitions/mongo/index.ts
example/nodejs/src/lib/stores/definitions/mysql/auditlog.ts
example/nodejs/src/lib/stores/definitions/mysql/index.ts
example/nodejs/src/routes/ping.ts
example/nodejs/src/stores/connection/mysql.ts
example/nodejs/src/stores/definitions/mongo/index.ts
example/nodejs/src/stores/definitions/mysql/index.ts
example/nodejs/src/stores/definitions/mysql/users.ts
example/nodejs/src/stores/index.ts
example/nodejs/src/stores/mongo.ts
example/nodejs/src/stores/mysql.ts

-
-
-
Before | After
:--: | :--:

New: 🎉  sequelize support

---

example/nodejs/src/stores/definitions/mongo/index.ts
example/nodejs/src/stores/definitions/mysql/index.ts
packages/nodejs/package.json
packages/nodejs/src/index.ts
packages/nodejs/src/stores/definitions/index.ts
packages/nodejs/src/stores/definitions/mongo/index.ts
packages/nodejs/src/stores/definitions/mysql/index.ts
packages/nodejs/src/stores/index.ts

- `packages/nodejs` の各モジュールを `index.ts` で連結するように変更
-
-
Before | After
:--: | :--:

Refactor: packages/nodejs exports

---

example/nodejs/src/domains/user.ts
example/nodejs/src/repositories/index.ts
example/nodejs/src/repositories/mongo/auditlogs.ts
example/nodejs/src/repositories/mongo/index.ts
example/nodejs/src/repositories/mongo/users.ts
example/nodejs/src/repositories/mysql/auditlogs.ts
example/nodejs/src/repositories/mysql/index.ts
example/nodejs/src/repositories/mysql/users.ts
example/nodejs/src/routes/ping.ts
example/nodejs/src/stores/definitions/mongo/index.ts
example/nodejs/src/stores/definitions/mongo/users.ts
example/nodejs/src/stores/definitions/mysql/index.ts
example/nodejs/src/stores/definitions/mysql/users.ts
packages/nodejs/src/domains/auditlog.ts
packages/nodejs/src/domains/index.ts
packages/nodejs/src/index.ts
packages/nodejs/src/stores/definitions/mongo/auditlogs.ts
packages/nodejs/src/stores/definitions/mongo/index.ts
packages/nodejs/src/stores/definitions/mysql/auditlogs.ts
packages/nodejs/src/stores/definitions/mysql/index.ts

- ストアを抽象化してユーザが mysql or mongo を意識しないようにする
- 
-
Before | After
:--: | :--:

Feature: abstract stores

---

.gitignore
docker-compose.example-nodejs.mongo.yml
docker-compose.example-nodejs.mysql.yml
example/nodejs/Dockerfile
example/nodejs/docker-compose.mongo.yml
example/nodejs/docker-compose.mysql.yml
example/nodejs/src/config.ts
example/nodejs/src/helpers/ssl.ts

- ssl周りの実装を微修正
-
-
Before | After
:--: | :--:

Fix: ssl for example

---

example/nodejs/src/config.ts
example/nodejs/src/routes/auth.ts
packages/nodejs/src/helpers/cookies.ts

- cookieにpathとmaxAgeがセットされるようにした
- オプションを渡しやすくした
-
-
Before | After
:--: | :--:

Fix: set cookie default path

---

example/nodejs/src/openapi/users.yaml
packages/nodejs/__tests__/domains/adminrole.test.ts
packages/nodejs/__tests__/domains/oas.test.ts
packages/nodejs/src/domains/oas.ts
packages/nodejs/src/openapi/adminroles.yaml
packages/nodejs/src/openapi/adminusers.yaml
packages/nodejs/src/openapi/auditlogs.yaml
packages/nodejs/src/openapi/oas.yaml

Fix: oas extended fields

---

packages/app/src/components/request/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_content/_table/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_content/hooks.ts
packages/app/src/pages/endpoints/[endpointId]/_content/index.tsx
packages/app/src/pages/endpoints/[endpointId]/index.tsx
packages/app/src/pages/home/_add/index.tsx
packages/app/src/pages/home/_auth/index.tsx
packages/app/src/pages/oauthredirect/index.tsx
packages/app/src/types/index.ts
packages/app/src/types/oas.ts
packages/app/src/utils/oas/index.ts
packages/app/src/utils/oas/style.ts
packages/website/docs/auth.md
packages/website/docs/template_literal.md

API call with default payload

---

example/nodejs/src/openapi/purchases.yaml

Fix: purchases.yaml

---

packages/app/src/components/pagination/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_content/_parts/pagination/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_content/index.tsx
packages/app/src/types/oas.ts

`GET /purchases?size=4&page=2`のレスポンスが常に一緒なんですが、ただ単にサーバ側が未実装なだけ・・？
```json
{
currentPage: 1,
list: [{}, {}, ,,,,,, {}],
maxPage: 15,
}
```

Pagination

---

example/nodejs/src/domains/purchase.ts
example/nodejs/src/domains/user.ts
example/nodejs/src/repositories/index.ts
example/nodejs/src/repositories/mongo/purchases.ts
example/nodejs/src/repositories/mongo/users.ts
example/nodejs/src/repositories/mysql/purchases.ts
example/nodejs/src/repositories/mysql/users.ts
example/nodejs/src/routes/purchases.ts
example/nodejs/src/routes/users.ts

Fix: paging

---

packages/app/src/pages/theme/_constants/index.ts
packages/app/src/pages/theme/_parts/chip/index.tsx
packages/app/src/pages/theme/_parts/label/index.tsx
packages/app/src/pages/theme/_types/index.ts
packages/app/src/pages/theme/_utils/index.ts
packages/app/src/pages/theme/index.tsx
packages/app/src/styles/global.css

テーマに応じた色を生成するツール

---

example/nodejs/src/application.ts
example/nodejs/src/security_handlers/jwt.ts
example/nodejs/src/stores/definitions/mongo/index.ts
example/nodejs/src/stores/definitions/mysql/index.ts
packages/nodejs/__tests__/domains/adminuser.test.ts
packages/nodejs/__tests__/domains/auth/googleoauth2.test.ts
packages/nodejs/__tests__/domains/auth/jwt.test.ts
packages/nodejs/__tests__/domains/auth/signout.test.ts
packages/nodejs/__tests__/fixtures/setup_mongo.ts
packages/nodejs/__tests__/fixtures/setup_repositories.ts
packages/nodejs/src/constants.ts
packages/nodejs/src/domains/auth/jwt.ts
packages/nodejs/src/domains/auth/signout.ts
packages/nodejs/src/repositories/index.ts
packages/nodejs/src/repositories/mongo/index.ts
packages/nodejs/src/repositories/mongo/revokedtokens.ts
packages/nodejs/src/repositories/mysql/index.ts
packages/nodejs/src/repositories/mysql/revokedtokens.ts
packages/nodejs/src/stores/definitions/mongo/index.ts
packages/nodejs/src/stores/definitions/mongo/revokedtokens.ts
packages/nodejs/src/stores/definitions/mysql/index.ts
packages/nodejs/src/stores/definitions/mysql/revokedtokens.ts

サインアウト機能を実装しました
- サインアウトしたときにトークンをDBに入れる
- トークン検証時にサインアウト済みのトークンかどうかチェック

Add: signout

---

packages/nodejs/src/domains/adminrole.ts

Fix: temporary fix hasPermission

---

codepipeline/discovery-buildspec.yml
codepipeline/discovery-deployspec.yml
package-lock.json
packages/website/docusaurus.config.js

[x] website用のcodepipelineを追加
[x] docusaurusのconfigを修正

Next codepipeline

---

example/nodejs/src/application.ts
example/nodejs/src/middlewares/auditlog.ts
example/nodejs/src/openapi/ping.yaml
example/nodejs/src/repositories/mongo/purchases.ts
example/nodejs/src/repositories/mongo/users.ts
example/nodejs/src/repositories/mysql/purchases.ts
example/nodejs/src/repositories/mysql/users.ts
example/nodejs/src/routes/adminaccounts.ts
example/nodejs/src/routes/index.ts
example/nodejs/src/security_handlers/jwt.ts
packages/nodejs/README.md
packages/nodejs/src/constants.ts
packages/nodejs/src/domains/adminaccount.ts
packages/nodejs/src/domains/adminuser.ts
packages/nodejs/src/domains/auditlog.ts
packages/nodejs/src/domains/index.ts
packages/nodejs/src/domains/oas.ts
packages/nodejs/src/helpers/repositories.ts
packages/nodejs/src/openapi/adminaccounts.yaml
packages/nodejs/src/openapi/adminroles.yaml
packages/nodejs/src/repositories/mongo/adminusers.ts
packages/nodejs/src/repositories/mongo/auditlogs.ts
packages/nodejs/src/repositories/mongo/revokedtokens.ts
packages/nodejs/src/repositories/mysql/adminusers.ts
packages/nodejs/src/repositories/mysql/auditlogs.ts
packages/nodejs/src/repositories/mysql/revokedtokens.ts

[x] クエリパラメータのバグ修正
[x] defaultParametersValue
[x] auditlogのミドルウェア追加
[x] READMEちょい足し

Next example

---

packages/nodejs/README.md
packages/nodejs/__tests__/domains/adminrole.test.ts
packages/nodejs/src/domains/adminrole.ts
packages/nodejs/src/domains/auth/email.ts
packages/nodejs/src/domains/auth/googleoauth2.ts

[x] README追記
[x] google認証で初回ログイン時に自動でユーザー作成するように修正
[x] viewerの権限を固定するように変更

Fix: adminusers/roles

---

example/nodejs/src/config/local.ts
packages/nodejs/src/helpers/repositories.ts
packages/nodejs/src/repositories/mysql/adminusers.ts
packages/nodejs/src/stores/definitions/mysql/adminusers.ts

MySQLの動作を調整

---

packages/app/src/pages/home/_endpoint/_signin/index.tsx
packages/app/src/pages/home/_endpoint/_signout/index.tsx

-
-
-
Before | After
:--: | :--:

Fix: resolve document.

---

example/nodejs/src/domains/article.ts
example/nodejs/src/openapi/articles.yaml
example/nodejs/src/repositories/index.ts
example/nodejs/src/repositories/mongo/articles.ts
example/nodejs/src/repositories/mongo/index.ts
example/nodejs/src/repositories/mysql/articles.ts
example/nodejs/src/repositories/mysql/index.ts
example/nodejs/src/routes/articles.ts
example/nodejs/src/routes/index.ts
example/nodejs/src/sampledata/articles.ts
example/nodejs/src/sampledata/index.ts
example/nodejs/src/stores/definitions/mongo/articles.ts
example/nodejs/src/stores/definitions/mongo/index.ts
example/nodejs/src/stores/definitions/mysql/articles.ts
example/nodejs/src/stores/definitions/mysql/index.ts

Add: example articles

---

codepipeline/app-deployspec.yml
codepipeline/snapshot-app-deployspec.yml

Enabled cloudfront cache invalidation

---

packages/golang/constant/constant.go
packages/golang/domains/adminroles.go
packages/golang/helpers/oas.go

Add: permission `all` and method `patch`

---

example/nodejs/package.json
package-lock.json
packages/nodejs/package.json

-
-
-
Before | After
:--: | :--:

Update: lib version

---

example/nodejs/package.json
package-lock.json
packages/nodejs/package.json
packages/nodejs/src/errors.ts
packages/nodejs/src/repositories/index.ts

-
-
-
Before | After
:--: | :--:

Fix: casbin adapter

---

example/nodejs/src/config/development.ts
example/nodejs/src/config/production.ts

-
-
-
Before | After
:--: | :--:

Fix: media bucket-name

---

example/nodejs/src/controllers/oas.ts

-
-
-
Before | After
:--: | :--:

Fix: set `x-viron-authtypes-path` when request to endpoint.

---

packages/golang/domains/auth/email.go
packages/golang/routes/auth/auth.go

- emailでのsigninもhttp.Requestが必要

🐛Fix：email signin param mod

---

example/nodejs/package.json
package-lock.json
packages/nodejs/package.json

fix(all): eslint 7.x

---

packages/golang/domains/oas.go

🐛Fix：listContentsByOasの処理を修正

---

packages/golang/domains/oas.go
packages/golang/helpers/slice.go

🐛Fix：aclAllow()

---

.changeset/wicked-eyes-clean.md
.gitmessage
commitlint.config.js
packages/app/CHANGELOG.md
packages/app/package.json

version(app): release

---

.changeset/little-cameras-speak.md
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/general.md
.github/PULL_REQUEST_TEMPLATE/version.md
commitlint.config.js
package-lock.json
packages/website/docs/05-References/changelog.md

PR Templates / Document / Fixes

---

example/golang/pkg/config/config.go

vironのprdとdevをexampleのAllowOriginsに追加

Add: cors for example golang

---

.changeset/dry-badgers-speak.md
.changeset/gold-cows-nail.md
.changeset/lazy-glasses-tell.md
.changeset/little-candles-eat.md
.changeset/small-parents-switch.md
.changeset/smart-berries-begin.md
.changeset/spicy-poets-notice.md
.changeset/three-pens-yawn.md
packages/app/CHANGELOG.md
packages/app/package.json
packages/website/CHANGELOG.md
packages/website/package.json

version(all): website and app

---

.changeset/lemon-olives-knock.md
packages/app/src/components/table/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/action/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/head/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/sibling/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/types/table/index.tsx
packages/app/src/portals/popover/index.tsx

Fix to put together all sibling and descendant operations in a content.
- #572

put together all sibling and descendant operations

---

.changeset/few-dancers-watch.md
packages/app/src/components/table/cell/array/index.tsx
packages/app/src/components/table/cell/boolean/index.tsx
packages/app/src/components/table/cell/index.tsx
packages/app/src/components/table/cell/numeric/index.tsx
packages/app/src/components/table/cell/object/index.tsx
packages/app/src/components/table/cell/string/index.tsx
packages/app/src/components/table/index.tsx
packages/app/src/types/oas.ts
packages/website/docs/04-Advanced-Guides/07-content-table.md

Added `uri-image` to display data with the `<img>` HTML tag.
- #570

Image Data in a table cell

---

.changeset/loud-jars-float.md
packages/app/src/components/table/cell/index.tsx
packages/app/src/components/table/cell/nullish/index.tsx
packages/app/src/layouts/index.tsx
packages/app/src/pages/index.tsx
packages/app/src/wrappers/root.tsx

Mobile Layout and Bug Fix

---

.changeset/few-dancers-watch.md
.changeset/lemon-olives-knock.md
.changeset/loud-jars-float.md
packages/app/CHANGELOG.md
packages/app/package.json
packages/website/CHANGELOG.md
packages/website/package.json

app v2.1.0 / website v0.3.0

---

packages/golang/domains/adminusers.go
packages/golang/domains/adminusers_test.go
packages/golang/repositories/mongo/adminusers/persistences.go
packages/golang/repositories/mysql/adminusers/persistences.go
packages/golang/routes/adminusers/adminusers.go

✨Update：adminuser remove api add

---

.changeset/flat-wasps-report.md
packages/app/src/utils/oas/index.ts
packages/app/static/oas.json
packages/app/static/shops

Fixed to recursively merge schemas in a `allOf` property.
Provide references that relate to your PR, if any.
- #598

fix(app): allOf handling

---

.changeset/wild-rivers-look.md
packages/app/src/components/table/index.tsx
packages/app/static/oas.json

Provide references that relate to your PR, if any.
- #607

Table with Popover UI

---

.changeset/flat-wasps-report.md
.changeset/wild-rivers-look.md
packages/app/CHANGELOG.md
packages/app/package.json

version(app): 2.2.0

---

example/golang/README.md

➕Add: example api README.md

---

package-lock.json
package.json
packages/nodejs/package.json

version: update node viron/lib version

---

codepipeline/app-buildspec.yml
codepipeline/app-deployspec.yml
codepipeline/snapshot-app-buildspec.yml
codepipeline/snapshot-app-deployspec.yml
packages/nodejs/package.json

During the publishing process in Viron, end-to-end testing is executed. 
It is necessary to install the dependencies required for E2E testing.
Provide references that relate to your PR, if any.
- #657

Install dependencies for E2E Testing

---

.changeset/selfish-windows-camp.md
packages/app/src/locales/en/common.json
packages/app/src/locales/ja/common.json
packages/app/src/pages/dashboard/_/appBar/export/index.tsx
packages/app/src/pages/dashboard/_/appBar/import/index.tsx
packages/app/src/pages/dashboard/_/tabs/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/add/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/info/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/qrcode/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/signin/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/signout/index.tsx
packages/app/src/pages/dashboard/groups/_/body/index.tsx

I18n support for dashboard.
en
ja

I18n support for dashboard

---

.changeset/many-teachers-own.md
packages/app/gatsby-config.js
packages/app/src/components/navigation/links/index.tsx

fix: remove language selector

---

.changeset/tame-cats-yell.md
packages/app/src/components/button/outline/index.tsx
packages/app/src/components/icon/more/outline/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx

feat(app): update endpoints item desgin

---

.changeset/stupid-turkeys-burn.md
package-lock.json
packages/app/package.json

Update gatsby version

---

codepipeline/app-buildspec.yml
codepipeline/snapshot-app-buildspec.yml

npm ci on Root

---

codepipeline/app-buildspec.yml
codepipeline/snapshot-app-buildspec.yml

Revert "npm ci on Root"

---

package-lock.json
packages/app/package.json

watcher@2.2 seems not working.

fix: watcher version

---

package-lock.json
packages/app/package.json

Revert "fix: watcher version"

---

.changeset/chilled-carrots-hammer.md
.changeset/empty-ads-destroy.md
.changeset/few-stingrays-worry.md
.changeset/friendly-years-serve.md
.changeset/funny-dryers-hug.md
.changeset/fuzzy-rocks-applaud.md
.changeset/gold-stingrays-march.md
.changeset/kind-readers-invent.md
.changeset/proud-experts-guess.md
.changeset/quick-pans-run.md
.changeset/red-houses-move.md
.changeset/stupid-turkeys-burn.md
.changeset/swift-toys-fly.md
.changeset/tame-cats-yell.md
.changeset/tame-parrots-fix.md
.changeset/thick-files-explain.md
.changeset/unlucky-panthers-rule.md
packages/app/CHANGELOG.md
packages/app/package.json
packages/linter/CHANGELOG.md
packages/linter/package.json
packages/nodejs/CHANGELOG.md
packages/nodejs/package.json

app 2.4.0, lib 2.1.0, linter 0.0.2

---

.changeset/sixty-planets-move.md
package-lock.json
packages/app/src/components/navigation/internalPages/index.tsx
packages/app/src/components/navigation/languages/index.tsx
packages/app/src/constants/index.ts
packages/app/src/layouts/index.tsx
packages/app/src/locales/en/common.json
packages/app/src/locales/ja/common.json
packages/app/src/pages/dashboard/_/navigation/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
packages/app/src/pages/dashboard/groups/_/body/index.tsx

fix: dashboard styles

---

package-lock.json
packages/nodejs/CHANGELOG.md
packages/nodejs/package.json

set caret on mongoose version

---

.changeset/calm-pandas-ring.md
packages/app/src/components/breadcrumb/index.tsx
packages/app/src/components/icon/arrowLeft/outline/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/appBar/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/navigation/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/navigation/pages/index.tsx
packages/app/src/pages/endpoints/[endpointId]/index.tsx
packages/app/tailwind.config.js

Update endpoint design
before | after (pc) | after (mobile)
-|-|-

Update endpoint design

---

.changeset/short-pigs-compete.md
package-lock.json
packages/app/src/pages/endpoints/[endpointId]/_/navigation/pages/index.tsx

- [feat(app): add file tree border](https://github.com/cam-inc/viron/commit/a9a6c78b775c39cd319e00f26d3fbd1b87bffa41)
before|after
-|-

Feat(app): add file tree border

---

.changeset/curvy-adults-attend.md
packages/app/src/components/button/filled/index.tsx
packages/app/src/components/button/outline/index.tsx
packages/app/src/components/button/outline/on/index.tsx
packages/app/src/components/error/index.tsx
packages/app/src/components/logo/index.tsx
packages/app/src/components/navigation/services/index.tsx
packages/app/src/pages/dashboard/_/navigation/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/info/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/thumbnail/index.tsx
packages/app/src/pages/index.tsx
packages/app/tailwind.config.js

| | before | after |
| -- | -- | -- |
| root | ![image](https://github.com/cam-inc/viron/assets/54166240/bbc04d62-8387-4a29-9d4a-e96015b18f7d)| ![image](https://github.com/cam-inc/viron/assets/54166240/ec1136be-8652-430c-806a-7aa881fd50f9)|
| dashboard |  ![image](https://github.com/cam-inc/viron/assets/54166240/e074da0a-2db2-4326-8597-35885ecda9c6)| ![image](https://github.com/cam-inc/viron/assets/54166240/aa2459f8-450c-4f57-8615-42be99cee56e)|

Fix:  root page & dashboard page styles

---

.changeset/chilly-lizards-fold.md
.changeset/smart-cars-promise.md
package-lock.json
packages/app/CHANGELOG.md
packages/app/package.json

version: 2.6.1

---

.changeset/olive-tools-join.md
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx

fix: endpoints empty

---

.changeset/fuzzy-lemons-talk.md
packages/app/src/components/button/filled/index.tsx
packages/app/src/components/button/icon/on/index.tsx
packages/app/src/components/icon/close/fill/index.tsx
packages/app/src/components/select/index.tsx
packages/app/src/components/textinput/index.tsx
packages/app/src/locales/en/common.json
packages/app/src/locales/ja/common.json
packages/app/src/pages/dashboard/endpoints/_/body/add/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
packages/app/src/portals/modal/index.tsx

Add endpoint

---

.changeset/rare-beds-rest.md
.changeset/soft-nails-swim.md
packages/app/CHANGELOG.md
packages/app/package.json

chore: app 2.9.0

---

.changeset/wild-guests-protect.md
packages/app/CHANGELOG.md
packages/app/package.json

App 2.10.0

---

.changeset/honest-tools-allow.md
packages/app/src/components/Skelton/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx

- update pending dashboard item
| isPending === true  | isPending === false |
| ------------- | ------------- |
|  <img width="1046" alt="スクリーンショット 2023-09-27 午後2 09 15" src="https://github.com/cam-inc/viron/assets/64121276/7931f0ee-44ee-4679-be31-b1d03f4a9f98"> | <img width="1045" alt="スクリーンショット 2023-09-27 午後2 08 40" src="https://github.com/cam-inc/viron/assets/64121276/128a1a89-53d9-4a0a-9a45-0d70f663132c"> |

feat(app): update pending dashboard item

---

.changeset/few-ears-promise.md
.changeset/honest-tools-allow.md
package-lock.json
packages/app/CHANGELOG.md
packages/app/package.json

version(app): 2.11.0

---

.changeset/silver-students-run.md
packages/app/src/components/button/index.tsx
packages/app/src/components/table/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/types/table/index.tsx

- Stop propagation with the sticky td tag
| before | after |
|------- | ----- |
| ![before](https://github.com/cam-inc/viron/assets/64121276/e59cb091-0d72-4c08-adf3-c9ed9091aca7) | ![after](https://github.com/cam-inc/viron/assets/64121276/7fddf9be-f29e-4d97-825e-2323b2d4244e) |

fix(app): add stopPropagation to sticky td tag

---

.changeset/five-lobsters-hammer.md
.changeset/silver-students-run.md
packages/app/CHANGELOG.md
packages/app/package.json

App 2.11.1

---

.changeset/four-jokes-switch.md
packages/app/CHANGELOG.md
packages/app/package.json

version(app): 2.11.2

---

packages/nodejs/src/domains/adminrole.ts

fix:casbin_locadpolicyされないバグ

---

packages/nodejs/package.json

fix:casbin_locadpolicyされないバグ vup忘れ

---

codepipeline/package-deployspec.yml

chore: update runtime version

---

.changeset/calm-lies-reflect.md
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/body/index.tsx

To reduce strange rattling of a spinner, place it to center of content container.
N/A

refactor(app): reduce CLS of Loader in content container 📦

---

.changeset/calm-lies-reflect.md
.changeset/tall-bikes-invite.md
packages/app/CHANGELOG.md
packages/app/package.json

chore(app): patch release v2.11.3 ♻️

---

codepipeline/demo-buildspec.yml

fix: failed to build docker image for demo.

---

.changeset/grumpy-mirrors-build.md
packages/app/src/components/request/index.tsx
packages/app/src/components/schema/types/array/index.tsx
packages/app/src/locales/en/common.json
packages/app/src/locales/ja/common.json
packages/app/src/pages/dashboard/groups/_/body/add/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/action/index.tsx

Fixed missing Japanese localization in the following locations.
|before(en)|after(jp)|
|-|-|
|<img width="500" alt="スクリーンショット 2024-01-12 午後5 05 18" src="https://github.com/cam-inc/viron/assets/75605907/efdf769e-2a75-4798-b85e-c75b44a4ef92">|<img width="500" alt="スクリーンショット 2024-01-12 午後5 05 42" src="https://github.com/cam-inc/viron/assets/75605907/644807a9-90b1-47b2-9a78-417af4e98a77">|
|before(en)|after(jp)|
|-|-|
|before(en)|after(jp)|
|-|-|
https://www.notion.so/cyberagent-group/000e93a674ef4f8f89187cb61b905311

Fix localization

---

.changeset/cool-planes-clap.md
.changeset/fair-pears-tap.md
.changeset/grumpy-mirrors-build.md
.changeset/quiet-ladybugs-smell.md
packages/app/CHANGELOG.md
packages/app/package.json

version(app): 2.11.5

---

.changeset/seven-horses-wash.md
package-lock.json
packages/website/docs/03-Guides/03-your-first-number-content.md
packages/website/docs/03-Guides/04-your-first-table-content.md
packages/website/docs/04-Advanced-Guides/environmental-variable.md
packages/website/docs/04-Advanced-Guides/lib.md
packages/website/docusaurus.config.js
packages/website/i18n/ja/docusaurus-plugin-content-docs/current/03-Guides/03-your-first-number-content.md
packages/website/i18n/ja/docusaurus-plugin-content-docs/current/03-Guides/04-your-first-table-content.md
packages/website/i18n/ja/docusaurus-plugin-content-docs/current/04-Advanced-Guides/environmental-variable.md
packages/website/package.json
packages/website/src/css/custom.css
packages/website/src/pages/index.js

feat(website): update docusaurus v3✨

---

.changeset/wise-lies-travel.md
packages/app/src/errors/index.ts
packages/app/src/hooks/endpoint.ts
packages/app/src/locales/en/common.json
packages/app/src/locales/ja/common.json
packages/app/src/pages/dashboard/endpoints/_/body/item/edit/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx

Modify endpoint

---

.changeset/blue-mayflies-pretend.md
.changeset/seven-horses-wash.md
.changeset/twelve-ducks-rhyme.md
.changeset/wise-lies-travel.md
packages/app/CHANGELOG.md
packages/app/package.json
packages/website/CHANGELOG.md
packages/website/package.json

version(app): 2.12.0

---

.changeset/plenty-gifts-unite.md
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx

Implement DnD for each group
https://github.com/cam-inc/viron/assets/75605907/3960e826-6035-4695-a943-b4767d048563

fix(app): implement DnD for each group

---

package-lock.json

not install from a private package

fix(nodejs): chore update

---

.changeset/breezy-socks-fry.md
packages/app/src/constants/index.ts
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx

group dnd bug fixes and refactorings

fix(app): group dnd bug fixes and refactorings

---

example/nodejs/package.json
package-lock.json

Fixed a type error in the Example application.
@types/multer-s3 major version up.
https://github.com/cam-inc/viron/pull/764

chore(example): update types♻️

---

.changeset/breezy-socks-fry.md
.changeset/old-insects-occur.md
package-lock.json
packages/app/CHANGELOG.md
packages/app/package.json
packages/nodejs/CHANGELOG.md
packages/nodejs/package.json

version: update

---

.github/workflows/publish-package-viorn-lib.yml
.github/workflows/publish-package-viorn-linter.yml

https://github.com/cam-inc/viron/actions/runs/8519950520

ci(): update actions

---

packages/app/src/components/error/index.tsx
packages/app/src/errors/index.ts
packages/app/src/hooks/endpoint.ts
packages/app/src/locales/en/common.json
packages/app/src/locales/ja/common.json
packages/app/src/pages/dashboard/_/menu/export/index.tsx
packages/app/src/pages/dashboard/_/menu/import/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/qrcode/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/signin/index.tsx
packages/app/src/pages/dashboard/endpoints/_/body/item/signout/index.tsx
packages/app/src/pages/dashboard/groups/_/body/index.tsx
packages/app/src/pages/dashboard/groups/_/body/item/index.tsx
packages/app/src/pages/endpointimport/_/body/index.tsx
packages/app/src/pages/endpoints/[endpointId]/_/content/hooks/useBase.ts
packages/app/src/pages/endpoints/[endpointId]/_/content/hooks/useDescendants.ts
packages/app/src/pages/endpoints/[endpointId]/_/content/hooks/useSiblings.ts
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/head/index.tsx
packages/app/src/pages/oauthredirect/_/body/index.tsx
packages/app/src/portals/modal/index.tsx
packages/app/src/wrappers/root.tsx

Display details in error modal when api communication fails

feat(app): add error modal

---

.changeset/loud-jobs-serve.md
packages/website/docs/04-Advanced-Guides/authentication.md
packages/website/i18n/ja/docusaurus-plugin-content-docs/current/04-Advanced-Guides/authentication.md

Write a summary of your PR here.

docs(website): wip about mode

---

docker-compose.example-nodejs.mongo.yml
docker-compose.example-nodejs.mysql.yml
example/nodejs/Dockerfile
example/nodejs/docker-compose.mongo.yml
example/nodejs/docker-compose.mysql.yml
example/nodejs/src/config/production.ts
example/nodejs/src/controllers/authconfigs.ts
example/nodejs/src/infrastructures/mysql/models/index.ts

fix(nodejs): dealing with ci failures

---

.github/workflows/publish-package-viorn-lib.yml
example/nodejs/package.json
example/nodejs/src/application.ts
example/nodejs/src/config/development.ts
example/nodejs/src/config/index.ts
example/nodejs/src/config/local.ts
example/nodejs/src/config/production.ts
example/nodejs/src/constants.ts
example/nodejs/src/controllers/adminroles.ts
example/nodejs/src/controllers/resources.ts
example/nodejs/src/domains/resources.ts
example/nodejs/src/middlewares/csrf.ts
example/nodejs/src/middlewares/errorhandler.ts
example/nodejs/src/openapi/components.yaml
example/nodejs/src/openapi/resources.yaml
example/nodejs/src/security_handlers/jwt.ts
package-lock.json
packages/nodejs/__tests__/domains/auth/oidc.test.ts
packages/nodejs/package.json
packages/nodejs/src/domains/adminaccount.ts
packages/nodejs/src/domains/adminrole.ts
packages/nodejs/src/domains/adminuser.ts
packages/nodejs/src/domains/auth/common.ts
packages/nodejs/src/domains/auth/email.ts
packages/nodejs/src/domains/auth/oidc.ts
packages/nodejs/src/errors.ts
packages/nodejs/src/openapi/adminroles.yaml
packages/nodejs/src/openapi/adminusers.yaml
packages/nodejs/src/openapi/components.yaml

fix(example): vulnerability Assessment Support

---

.changeset/fast-apples-switch.md
.changeset/loud-jobs-serve.md
.github/workflows/publish-package-viorn-lib.yml
example/nodejs/CHANGELOG.md
example/nodejs/package.json
packages/app/CHANGELOG.md
packages/app/package.json
packages/nodejs/CHANGELOG.md
packages/nodejs/package.json
packages/website/CHANGELOG.md
packages/website/package.json

fix(example,nodejs,app,website): changelog

---

packages/golang/domains/adminuserssotokens.go
packages/golang/repositories/adminuserssotokens.go

fix(golang): golang ssotokens tokenType lower case

---

.changeset/loud-spiders-promise.md
packages/app/src/pages/endpoints/[endpointId]/_/content/parts/body/index.tsx

Display errors in descendant operations
- https://github.com/cam-inc/viron/pull/828

fix: display errors in descendant operations

---

.changeset/little-feet-remember.md
.changeset/loud-spiders-promise.md
package-lock.json
packages/app/CHANGELOG.md
packages/app/package.json
packages/nodejs/CHANGELOG.md
packages/nodejs/package.json
packages/website/package.json

feat: release lib 2.6.0 ✨
